- name: openwisp_users present in settings.py?
  shell: >
    file {{ openwisp2_path }}/openwisp2/settings.py > /dev/null 2>&1 &&
    grep openwisp_users {{ openwisp2_path }}/openwisp2/settings.py | wc -l
  failed_when: false
  changed_when: false
  register: openwisp_users_check

# perform migration to multitenant version of OpenWISP 2
- include: multitenancy_migration.yml
  when: openwisp_users_check.rc == 0 and openwisp_users_check.stdout == "0"

- name: create {{ openwisp2_path }}
  file:
    path: "{{ openwisp2_path }}"
    state: directory
    group: www-data
    mode: 0775

- name: create "{{ openwisp2_path }}/openwisp2"
  file:
    path: "{{ openwisp2_path }}/openwisp2"
    state: directory
    group: www-data
    mode: 0775

- name: create "{{ openwisp2_path }}/log"
  file:
    path: "{{ openwisp2_path }}/log"
    state: directory
    group: www-data
    mode: 0775

- name: manage.py
  notify: reload supervisor
  template:
    src: ../templates/manage.py
    dest: "{{ openwisp2_path }}/manage.py"
    group: www-data
    mode: 0754

- name: __init__.py
  notify: reload supervisor
  template:
    src: ../templates/openwisp2/__init__.py
    dest: "{{ openwisp2_path }}/openwisp2/__init__.py"
    group: www-data

- name: urls.py
  notify: reload supervisor
  template:
    src: ../templates/openwisp2/urls.py
    dest: "{{ openwisp2_path }}/openwisp2/urls.py"
    group: www-data

- name: wsgi.py
  notify: reload supervisor
  template:
    src: ../templates/openwisp2/wsgi.py
    dest: "{{ openwisp2_path }}/openwisp2/wsgi.py"
    group: www-data

# set openwisp2_secret_key if not defined explicitly
- include: django_secret_key.yml
  when: openwisp2_secret_key is not defined

- name: settings.py
  notify: reload supervisor
  template:
    src: ../templates/openwisp2/settings.py
    dest: "{{ openwisp2_path }}/openwisp2/settings.py"
    group: www-data

- name: migrate
  notify: reload supervisor
  become: yes
  become_user: www-data
  django_manage:
    app_path: "{{ openwisp2_path }}"
    command: migrate
    virtualenv: "{{ virtualenv_path }}"

- name: set permissions to sqlite db
  when: openwisp2_database.engine == "django.db.backends.sqlite3"
  file:
    path: "{{ openwisp2_database.name }}"
    state: file
    group: www-data
    mode: 0775

- name: collectstatic
  notify: reload supervisor
  become: yes
  become_user: www-data
  django_manage:
    app_path: "{{ openwisp2_path }}"
    command: "collectstatic --noinput"
    virtualenv: "{{ virtualenv_path }}"

- name: load create_superuser.py script
  template:
    src: ../templates/create_superuser.py
    dest: "{{ openwisp2_path }}/create_superuser.py"
    mode: 0754

- name: create superuser and default org
  shell: "env/bin/python create_superuser.py"
  register: superuser_result
  changed_when: '"created" in superuser_result.stdout'
  args:
    chdir: "{{ openwisp2_path }}"
