- name: create "{{ app_path }}/public_html"
  file:
    path: "{{ app_path }}/public_html"
    state: directory

- name: create "{{ app_path }}/ssl"
  file:
    path: "{{ app_path }}/ssl"
    state: directory

- name: create SSL cert if not exists yet
  command: >
    openssl req -new -nodes -x509 -subj "/C={{ ssl_country }}/ST={{ ssl_state }}/L={{ ssl_locality }}/O={{ ssl_organization }}/CN={{ ssl_common_name }}" -days 3650 -keyout {{ ssl_key }} -out {{ ssl_cert }} -extensions v3_ca creates={{ ssl_cert }}
  notify: restart nginx

- name: nginx site available
  template:
    src: ../templates/nginx.j2
    dest: "/etc/nginx/sites-available/{{ inventory_hostname }}"
  notify: restart nginx

- name: nginx site enabled
  file:
    src: "/etc/nginx/sites-available/{{ inventory_hostname }}"
    dest: "/etc/nginx/sites-enabled/{{ inventory_hostname }}"
    state: link
  notify: restart nginx
