- name: uwsgi.ini
  template:
    src: ../templates/uwsgi.ini.j2
    dest: "{{ openwisp2_path }}/uwsgi.ini"
  notify: reload supervisor

- name: supervisor uwsgi
  template:
    src: ../templates/supervisor/openwisp2.j2
    dest: "{{ supervisor_path | format('openwisp2') }}"
  notify: reload supervisor
