### openwisp2
## handlers
---

- name: reload systemd
  systemd: daemon_reload=yes
  when: ansible_distribution_release in ['jessie', 'xenial']

- name: reload supervisor
  command: supervisorctl reload

- name: restart nginx
  service: name=nginx state=restarted
